version: '3'

services:
  go-cryptocurrency-election:
    image: postgres:alpine
    ports:
      - '5430:5432'
    container_name: 'go-cryptocurrency-election'
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=go-cryptocurrency-election

volumes:
  database: